spring:
  application:
    name: item-service
  config:
    import: optional:configserver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      items:
        # El valor es el establecido en la linea 19
        base-config: default

  # Establecemos el timeOut
  timelimiter:
    configs:
      default:
        timeout-duration: 6s
    instances:
      items:
        base-config: default


server:
  port: 8081
